name: Rspec tests
on:
  repository_dispatch:
    types: [rspec-tests]
jobs:
  rspec-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
